# Dockerfile - Arquivo para construção de imagens
# Imagem - Template para construção de construção de container
# Container - Processo de imagem sendo executada

# Especificando imagem base com instalação de python
FROM python:3.8

# Adicionando arquivo .py do repositório atual no container
ADD adivinha_numero.py .

# Comando que vai ser executado por esse container
CMD ["python3", "/adivinha_numero.py"]